name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @Collection.
version: 3.1.0+1
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  # analyzer: ">=4.6.0 <6.0.0"
  # dart_style: ^2.2.3
  # source_gen: ^1.2.2
  # build: ^2.3.0
  analyzer: ">=7.1.0"
  dart_style: 3.0.1
  build: 2.4.2
  dartx: ^1.1.0
  glob: ^2.0.2
  isar: 3.1.0+1
  path: ^1.8.1
  source_gen: 2.0.0
  xxh3: ^1.0.1

dev_dependencies:
  build_test: ^2.1.5
  matcher: ^0.12.12
  test: ^1.21.0
  very_good_analysis: ^3.0.1
